### ISSUE TITLE
Old Predictions Redirect to Homepage

### ISSUE THREAD

**Issue by glenn-murray-bse** [tricycle/predictionbook#104]
Links:

http://predictionbook.com/predictions/30

http://predictionbook.com/predictions/395

The above predictions redirect to the homepage.

**Comment by ivan** [comment]
I think these are just private predictions?  I see the "You are not authorized to perform that action" message.

**Comment by glenn-murray-bse** [comment]
Yes, they are private, however they are being displayed on my "due_for_judgement" page.

http://predictionbook.com/users/glenn/due_for_judgement
