### ISSUE TITLE
URL somehow malformed for usernames with dot

### ISSUE THREAD

**Issue by notionparallax** [tricycle/predictionbook#109]
Recently any pages related specificly to me have stopped working.
My guess is that it's something to do with the way the URL is interpreting the dot. %5B  D are square brackets. It might be .to_s ing an array?
If someone could point me at where the problem might be I could have a crack at a pr.

http://predictionbook.com/users/ben%5Bdot%5Ddoherty/due_for_judgement

**Comment by notionparallax** [comment]
Thanks for looking at this!
Is this still waiting to be deployed? I'm still getting the same behaviour.

**Comment by moggyboy** [comment]
Sorry @notionparallax this fix doesn't fix the described issue at all. [This](https://github.com/tricycle/predictionbook/commit/925a6792733fa3ffce815db4618f86876f901fe9) does and I'll deploy first thing tomorrow Melbourne time.
