### ISSUE TITLE
URGENT: Unable to log in

### ISSUE THREAD

**Issue by vipulnaik** [tricycle/predictionbook#132]
I go to https://predictionbook.com/users/sign_in and enter my correct username (vipulnaik) and password for that username. I am then redirected to the homepage, but still show up as not logged in. When I go to my predictions I am unable to edit them.

I'm pretty sure it's the correct password, because when I enter the wrong password I am returned to the login page for another attempt.

I see the issue on Chrome both on my phone (Android OnePlus 3) and on my laptop (Mac OS X). There were no network or console error messages that could shed light on the issue.

**Comment by vipulnaik** [comment]
I was able to log in as recently as 7 days ago, so I am guessing that it must be the commits based between 7 days ago and today that broke the ability to login. Specifically, it must be the commits of September 19.

**Comment by moggyboy** [comment]
@vipulnaik @ethanbas @michaeldickens This is now fixed. Apologies for the inconvenience. This didn't affect users already logged in so we didn't pick it up in our sanity check test.

**Comment by moggyboy** [comment]
Fixed in f3c0928c3ea05689a7cf041c5a30c70e2ee1434c

**Comment by vipulnaik** [comment]
Thanks!
