### ISSUE TITLE
Login redirects to login page

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#135]
I notice I get redirected to login page when I attempt to login now,
'forgot password' fails for my email address with 
> Email not found

Is this an account issue or a site issue?

**Comment by moggyboy** [comment]
@themusicgod1 See https://predictionbook.com/predictions/182609 and https://predictionbook.com/predictions/178256

**Comment by moggyboy** [comment]
(That is - 1. an administrator giving you an explicit warning, which you ignored and provoked them to get you banned, and 2. your prediction of being banned being marked right)

**Comment by themusicgod1** [comment]
So let's get this straight.  You banned me because, despite citing sources verifying my claim, people keep judging my claims contrary to what I have offered evidence to be the case.

I would suggest this website needs visible rules, or at least some indication that administrators have the final say.  Let's review the public facing aspects of the site:

> Find out just how sure you should be, and get better at being only as sure as the facts justify.

Not "facts as far as gwern says they are" not "you have to make predictions that gwern approves  or finds to be to his taste" not "get better as being sure as the other people on this website feel is justified" not "you have to have a great accuracy before you come to predictionbook, don't bother making predictions otherwise" but "get better at being only as sure as the facts justify".  

I have done this.  I have promoted this website all over the internet.  If you look at twitter under predictionbook, the vast majority of the people who talk about it is me, for example.  You're right: I don't really care for gwern's opinion of me.  Where is it mentioned that I should?  It isn't.

You have removed a user because he finds the facts support his view on a claim.  This is by far not going to be the last time this happens so you better start getting a process to deal with conflicting version of the truth sooner, rather than later.
