### ISSUE TITLE
Can't resolve someone else's overdue conditional prediction, leading to perpetual overdue judgement warning

### ISSUE THREAD

**Issue by jbeshir** [tricycle/predictionbook#136]
Predictions need to be marked as right or wrong or withdrawn to stop them appearing as overdue.

Conditional predictions, if the condition isn't met, need to be withdrawn (because they are neither right nor wrong).

However, while you can judge someone else's prediction right or wrong, only the person who originally made the prediction can withdraw it. This means if you put a probability on someone else's conditional prediction, the condition fails to come to pass, and the person who originally made the prediction doesn't withdraw it, you are stuck with a perpetual overdue judgement warning at the top of every page.

This is affecting my account on the primary PredictionBook instance, because I made a prediction on https://predictionbook.com/predictions/182371, the condition did not come to pass, and it has not been withdrawn since.

A possible solution is to permit anyone who assigned a probability to withdraw an overdue prediction, and a more complex one is to permit a prediction to be judged as void.

**Comment by jaysonvirissimo** [comment]
In propositional logic, it is conventional to consider a condition statement with a false antecedent to be true. I'm in favor of adopting that convention for these cases, but that may not be fair for previously made predictions (assuming the predictor intended to withdraw it given the condition doesn't hold).
