### ISSUE TITLE
Can't delete account

### ISSUE THREAD

**Issue by ghost** [tricycle/predictionbook#139]
I can't find a way to delete my account. Something something GDPR? Oh well it's all good.

**Comment by jaysonvirissimo** [comment]
Yeah, letting the user delete their account from their settings page would make sense to me. On the other hand, deleting it outright could remove historical context from the predictions and comments. A possible solution would be to change all the references to the user's account to instead be associated with a special purpose deleted user account, so they are anonymized, but their wagers are still there. So, after the deletion a prediction page would look like this:
```
Foo will either bar or baz.
Created by deleted-user 3 days ago; known on 2020-01-01
```

**Comment by jaysonvirissimo** [comment]
The irony of me talking to a @ghost about this doesn't escape me.
