### ISSUE TITLE
User statistics: proper scoring rule

### ISSUE THREAD

**Issue by andre-l-github** [tricycle/predictionbook#3]
I would like user pages to include a more precise estimate of a user's quality - using a [proper scoring rule](http://en.wikipedia.org/wiki/Proper_scoring_rule#Logarithmic_scoring_rule). The simplest is the log scoring rule, which is very easy to implement. Here is a version in Haskell, excerpted from my Nootropics essay where I am judging my Adderall predictions:

you 'earn' the logarithm of the probability if you were right, and the logarithm of the negation if you were wrong; he who racks up the fewest negative points wins. We feed in a list and get back a number:

``` .haskell
logScore ps = sum $ map (\(result,p) -> if result then log p else log (1-p)) ps
logScore [(True,0.95),(False,0.30),(True,0.85),(True,0.75),(False,0.50),(False,0.25),(False,0.60),(True,0.70),(True,0.65),(True,0.60),(False,0.30),(True,0.50),(True,0.90),(True,0.40)]
~> -6.125
```

In this case, a blind guesser would guess 50% every time (roughly half the days were Adderall and roughly half were not) so the question is, did the 50% guesser beat me?

``` .haskell
(15 * log 0.5)
~> -10.397
(15 * log 0.5) > logScore [(True,0.95),(False,0.30),(True,0.85),(True,0.75),(False,0.50),(False,0.25),(False,0.60),(True,0.70),(True,0.65),(True,0.60),(False,0.30),(True,0.50),(True,0.90),(True,0.40)]
~> False
```

So I had a palpable edge over the random guesser, although the sample size is not fantastic.

---

The best way would be to divide the log score of the equivalent number of 50% guesses - since every prediction on PB.com is a binary prediction - by the user's actual log score. If you scored, say, -15 and the random guesser scored -20, then -20/-15=1.3. Higher is better; if later the random guesser has -25 and you have -17, you did even better since now you earned 1.47.

Scaling this up to PB users seems easy:  for the _n_ judged predictions, sum the logs of the last probability, and then divide with _n_ \* log 0.5.

Display-wise, this is easy: just report the number. In a user page like http://predictionbook.com/users/gwern one can probably just tack on an additional column to the row: like

```
| Score
| 1.47
```

**Comment by matthewfallshaw** [comment]
Implemented by #55 then, I think, removed for performance reasons. Anyone keen to try to improve #55 's performance?

**Comment by jaysonvirissimo** [comment]
[This](https://github.com/tricycle/predictionbook/pull/119) is more performant, but still needs a bit of work.

**Comment by moggyboy** [comment]
Will be rolled out tomorrow.
