### ISSUE TITLE
Add RESTful API

### ISSUE THREAD

**Issue by jaysonvirissimo** [tricycle/predictionbook#65]
An API that accepts JSON might be a good idea, since it would make creating command-line, smartphone, etc... apps much easier to create. I can namespace it under `api` so it doesn't require changing any existing routes or controller actions.

If no one objects or is already working on this, I can work on setting up the API and possibly a command-line client as well.

**Comment by matthewfallshaw** [comment]
No one is already working on this, and it sounds like a good idea.
Thanks for this and your other contributions, Jayson.

**Comment by RenWenshan** [comment]
that would be great, thank you

**Comment by jaysonvirissimo** [comment]
[Here](https://github.com/tricycle/predictionbook/pull/67) is a sample of what I had in mind.

**Comment by jaysonvirissimo** [comment]
[Here](https://github.com/tricycle/predictionbook/pull/71) is a limited implementation of this feature.

**Comment by jaysonvirissimo** [comment]
Done.
