### ISSUE TITLE
E-mail notification messages aren't being sent

### ISSUE THREAD

**Issue by patbl** [tricycle/predictionbook#76]
About three weeks ago, I stopped receiving e-mail notifications when my predictions were due:

<img width="554" alt="screenshot 2015-09-18 00 55 49" src="https://cloud.githubusercontent.com/assets/1735266/9954710/0f007cbc-5da0-11e5-86ce-08cdf5401237.png">

**Comment by jaysonvirissimo** [comment]
I'll try to verify this when I get a chance.

**Comment by patbl** [comment]
I've stopped using the Prediction Book because I forget how my predictions turned out by the time I remember to visit the site. I hope this can be fixed—it's a pretty neat app!

**Comment by cattruscott** [comment]
Apologies folks, it should be all fixed now (and apologies it you get spammed by the backlog).

**Comment by jaysonvirissimo** [comment]
Seems to be working again.

**Comment by patbl** [comment]
Thanks for fixing it!
