### ISSUE TITLE
implement sitemap linking all public predictions

### ISSUE THREAD

**Issue by ivan** [tricycle/predictionbook#78]
Google can't index most of predictionbook, merely because predictionbook doesn't link to all of the public predictions (at least longer than the ~hour they stay on the homepage.)  As a result, out of the hundreds of predictions I've made, I can only find about a fifth of them on Google.

I think this could be fixed by either 1) paginating the predictions on user pages and having an index of all users, or 2) having a giant sequential index of all public predictions.

**Comment by ivan** [comment]
Or 3) a sitemap.xml that links to all the predictions.

**Comment by ivan** [comment]
In the meantime hopefully this index will help Google: https://ludios.org/predictionbook-index/

**Comment by ivan** [comment]
http://pbindex.neocities.org/

**Comment by jaysonvirissimo** [comment]
It looks like [this](4b66028a9a714054679c8f664366cb413a70dce4) more or less tackles this issue. We can close this out now.

**Comment by vipulnaik** [comment]
It seems like Google still misses predictions. For instance:

https://www.google.com/search?sitesearch=predictionbook.com&q=despacito&x=0&y=0

returns the homepage, from the time that prediction was on the homepage, but not the link to the actual prediction:

PredictionBook: How sure are you?
https://predictionbook.com/
Despacito will reach 2 billion YouTube video views on or before January 1, 2018, and will be the fastest song to have ever reached 2 billion views at the time it ...

For reference, the actual prediction is at https://predictionbook.com/predictions/182454
<img width="732" alt="screen shot 2017-06-16 at 7 37 00 pm" src="https://user-images.githubusercontent.com/7758551/27249480-5c889ba0-52cb-11e7-8b8e-83bc27070264.png">

**Comment by vipulnaik** [comment]
created new issue #123 to contain previous comment.
