### ISSUE TITLE
paginate user page

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#82]
if I go to http://predictionbook.com/users/themusicgod1 I'm noticing some of my older predictions are disappearing in the bottom with presumably no way to get to them other than 
a) having them emailed to me when they are ready to judge
b) remembering that they exist and searching for them(ugh). 

What I'd be interested in is a "judge in this order" page of some kind, so that I have some reminder of what information I'm supposed to be looking for.

**Comment by theminted** [comment]
Sounds like the easiest way to make the prediction list more usable is moving from a "Most Recent Predictions" to "Predictions" with pagination.

Further we could split each user into several views such as "Ready to Judge" etc.

You say you want a "judge in this order" page. Why is there a particular order in which predictions ought to be judged? I am unfortunately not that familiar with the repo and the application.

**Comment by themusicgod1** [comment]
> Why is there a particular order in which predictions ought to be judged?

I guess.  But then why do claims even have end dates?
