### ISSUE TITLE
prediction 'wager' count is wrong if you update your prediction

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#83]
suppose i make a claim, and then predict 51% that it will happen.

then i realize I had a typo and instead of typing 51% i typed 15%.  I go back and update my prediction to 51%.

Now it claims there are 2 wagers, and the average is (/ (+ 15 51) 2) = 33.  This is wrong.  It should accept one wager per person for the purposes of this count.

**Comment by jaysonvirissimo** [comment]
This seems like a restatement of [this](https://github.com/tricycle/predictionbook/issues/25) issue.

**Comment by themusicgod1** [comment]
yup. dupe!
