### ISSUE TITLE
SSL / HTTPS

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#84]
Am I seeing this right that predictionbook is http only?

For a password-protected site where our reputations are at stake, it's worth using SSL.  If for no other reason than with HTTP alone it's possible to inject javascript into your requests, subjecting your users to security risk there.

https://letsencrypt.org/

**Comment by jaysonvirissimo** [comment]
![secure-connection](https://cloud.githubusercontent.com/assets/1292454/25011301/c0d7fe16-2021-11e7-9040-4b0258b76db2.png)
This has been completed and this issue can be closed out.
