### ISSUE TITLE
sort by random() on user page

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#89]
this would actually kind of get rid of the need for a 'next' button or a 'search' really.

**Comment by matthewfallshaw** [comment]
I don't understand. Help me.

**Comment by themusicgod1** [comment]
right now, if I got to my user page, i only get the last 100 or so predictions.  Which is kind of annoying since i would like to be consistent with things I predicted more than 100 predictions ago... but I to be honest can't remember some fo them.  If every time I refreshed my user page it gave me 100 different things I've said, sooner or later it'd be likely that I'd see something relevant

**Comment by jaysonvirissimo** [comment]
Pagination of predictions on the user page would probably diminish this pain point as well as several others.

**Comment by themusicgod1** [comment]
it would for sure, but this is probably easier to implement.
i think how it works right now though which seems to be whatever claim was updated most recently is pretty handy though in a social way, so it's a hard call.

**Comment by matthewfallshaw** [comment]
prefer #82
wontfix
