### ISSUE TITLE
 as of may 26, 2016 'overdue predictions' includes duplicate prediction entries

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#92]
I have 2 predictions on http://predictionbook.com/predictions/22850 
and when i go to 'overdue predictions' it shows 2 entries for it:

Eliezer Yudkowsky has never read a book written by Andrea Dworkin. ( 76% confidence; 5 wagers; 5 comments )

Created by tedks on 2014-01-08; known on 2014-01-08.

Eliezer Yudkowsky has never read a book written by Andrea Dworkin. ( 76% confidence; 5 wagers; 5 comments )

Created by tedks on 2014-01-08; known on 2014-01-08.

that's kind of superfluous.

**Comment by themusicgod1** [comment]
same with 'user' page

**Comment by moggyboy** [comment]
I got this fixed, will roll out tomorrow morning Melbourne time.
