### ISSUE TITLE
new claims not showing up on user page

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#93]
"Most recent predictions by themusicgod1" is not, in fact, the most recent predictions by themusicgod1: just created a new claim, and it's not there, and the ones that are there are claims that I predicted quite awhile ago:

I'm not really sure the pattern.
http://0bin.net/paste/g9muoMH7nC15XCke#SHqGuFjWv-ItuYWujCPmaiSwpXkNqAY4VweLklAjaeH

**Comment by themusicgod1** [comment]
in fact it looks like it's the "least recent" rather than most recent.

**Comment by themusicgod1** [comment]
i'm not the only one.
http://predictionbook.com/users/mikeattrike

**Comment by themusicgod1** [comment]
https://github.com/tricycle/predictionbook/blob/master/app/controllers/predictions_controller.rb seems to call
https://github.com/tricycle/predictionbook/blob/master/app/models/prediction.rb recent(limit) 
which orders by 
"created_at: :desc"
this could be something like "updated_at: :asc"...but it looks like there's a version change there.

**Comment by themusicgod1** [comment]
https://github.com/tricycle/predictionbook/blob/master/app/controllers/users_controller.rb 

maybe 


def show
@title = "Most recent predictions by #{@user}"
@predictions = @user.predictions
@predictions = @predictions.not_private unless user_is_current_user?
@predictions = @predictions.limit(100)
end

to 

def show
@title = "Most recent predictions by #{@user}"
@predictions = @user.predictions
@predictions = @predictions.not_private unless user_is_current_user?
@predictions = @predictions.order("updated_by: :asc")
@predictions = @predictions.limit(100)
end

or something?

**Comment by moggyboy** [comment]
I got this fixed, will roll out tomorrow morning Melbourne time.
