### ISSUE TITLE
credence game answers seem backwards

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#94]
who's higher
The right answer is Paul Allen (22 billion USD) versus Warren Buffett (42 billion USD).

(guessed: warren buffett).
uh...

**Comment by themusicgod1** [comment]
another good example:
(which one is higher)
The right answer is Canada (629,900 GWh) versus United States (4,325,900 GWh).

**Comment by moggyboy** [comment]
I've taken the game down until I can work out what the author's intent was.

**Comment by moggyboy** [comment]
Fixed and reloaded credence games.
