### ISSUE TITLE
error in email notifications

### ISSUE THREAD

**Issue by sflicht** [tricycle/predictionbook#95]
I think this is a new bug in the latest release.
![pb](https://cloud.githubusercontent.com/assets/3683449/15643224/aafe5aec-267e-11e6-9770-32e23092be7d.PNG)

Google Chrome	50.0.2661.102 (Official Build) m (32-bit)
Revision	c26c0312e940221c424c2730ef72be2c69ac1b67-refs/branch-heads/2661@{#680}
OS	Windows 
Blink	537.36 (@c26c0312e940221c424c2730ef72be2c69ac1b67)
JavaScript	V8 5.0.71.48
Flash	21.0.0.242
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Command Line	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --flag-switches-begin --flag-switches-end --restore-last-session --flag-switches-begin --flag-switches-end

**Comment by moggyboy** [comment]
Fixed

**Comment by sflicht** [comment]
Cool, thanks!
