### ISSUE TITLE
'told you so' award

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#96]
if you're, for example, > 6 sigma over the mean guess, for some reason, > 6 sigma before the mean *time* of the guess, and you happen to be right...you should get a badge on your profile for being a lucky bastard.

**Comment by matthewfallshaw** [comment]
Yes, you totally should. This would be a nice feature to add.
Also, I hereby grant you one of our "if wishes were fishes" awards. This is unlikely to be implemented soon :)
