### ISSUE TITLE
can't log in today, no error

### ISSUE THREAD

**Issue by themusicgod1** [tricycle/predictionbook#97]
Nothing's changed on my end from yesterday: Pale moon browser Version: 26.0.1 (x64) on Ubuntu 15.10, just redirects me to http://predictionbook.com/users/sign_in whether I provide the correct username/password or not.

**Comment by sadhu89** [comment]
@themusicgod1 Are you still having this problem? Looks like the login is working fine.

**Comment by themusicgod1** [comment]
Yeah.

**Comment by themusicgod1** [comment]
pfft now it works.  PEBKAC?
